Added resultcard.js and resultcard.css to project guide folder. Featu…
acmutd/nebula-guide pull request #26
Opened 2022-04-16 05:11 UTC by nathan-s-williams

…re satisfies the requirements for 22-feature-request-result-cards. Function works by passing a JSON with endpoints articleid, title, description and image into props.

2022-04-18 19:27 UTC, ryan-radloff requested changes

2022-04-18 19:27 UTC, ryan-radloff commented on components/ResultCardComponent/ResultCards.js
> +const renderCard = (card) => {
File should be in typescript (.tsx) extension

2022-04-18 19:27 UTC, ryan-radloff commented on components/ResultCardComponent/ResultCards.js
> +const renderCard = (card) => {
Add brief comment describing what the component does

2023-02-09 19:14 UTC, WillieCubed commented
Closing as stale

2023-02-09 19:14 UTC, closed without merging